// <auto-generated />
namespace CovidNews.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_CountriesController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_CountriesController));
        
        string IMigrationMetadata.Id
        {
            get { return "202102161002002_add_CountriesController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
